_parent_: configs/base.yaml

tb: false
batch_size: 1                                                

log_sampler: true

data_test:
    ibrnet_llff_test:
        root_dir: data/llff
        dataset_name: ibrnet_llff_test                                          
        img_wh:                                  
        num_workers: 0                                        
        max_len: -1
        scene_list:
        test_views_method: nearest
